---
javascripts:
- base:
  - jquery.min
  - rails
  - jquery.placeholder
  - jquery-ui.min
  - jquery.multiselect
  - jquery.elastic
  - jquery.qtip.min
  - jquery.qtip.styles
  - application
stylesheets:
- base:
  - reset
  - jquery-ui
  - jquery.multiselect
  - styles

